services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/filestorage
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - JWT_SECRET_KEY=secret-key
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - BUCKET_ENDPOINT=http://minio:9000
      - BUCKET_ACCESS_KEY=admin
      - BUCKET_SECRET_KEY=password
    depends_on:
      - postgresql

  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=filestorage
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./.docker/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
